// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ohlc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date      string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	StockCode string `protobuf:"bytes,2,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Request) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

type Summary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Average       float64 `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	AverageRound  float64 `protobuf:"fixed64,2,opt,name=AverageRound,proto3" json:"AverageRound,omitempty"`
	Volume        int64   `protobuf:"varint,3,opt,name=Volume,proto3" json:"Volume,omitempty"`
	Value         int64   `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
	PreviousPrice int32   `protobuf:"varint,5,opt,name=PreviousPrice,proto3" json:"PreviousPrice,omitempty"`
	HighestPrice  int32   `protobuf:"varint,6,opt,name=HighestPrice,proto3" json:"HighestPrice,omitempty"`
	LowestPrice   int32   `protobuf:"varint,7,opt,name=LowestPrice,proto3" json:"LowestPrice,omitempty"`
	ClosePrice    int32   `protobuf:"varint,8,opt,name=ClosePrice,proto3" json:"ClosePrice,omitempty"`
	TotalTrans    int32   `protobuf:"varint,10,opt,name=TotalTrans,proto3" json:"TotalTrans,omitempty"`
}

func (x *Summary) Reset() {
	*x = Summary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{1}
}

func (x *Summary) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *Summary) GetAverageRound() float64 {
	if x != nil {
		return x.AverageRound
	}
	return 0
}

func (x *Summary) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Summary) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Summary) GetPreviousPrice() int32 {
	if x != nil {
		return x.PreviousPrice
	}
	return 0
}

func (x *Summary) GetHighestPrice() int32 {
	if x != nil {
		return x.HighestPrice
	}
	return 0
}

func (x *Summary) GetLowestPrice() int32 {
	if x != nil {
		return x.LowestPrice
	}
	return 0
}

func (x *Summary) GetClosePrice() int32 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *Summary) GetTotalTrans() int32 {
	if x != nil {
		return x.TotalTrans
	}
	return 0
}

var File_ohlc_proto protoreflect.FileDescriptor

var file_ohlc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x68, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x3c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xa1,
	0x02, 0x0a, 0x07, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x41, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x50,
	0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x32, 0x3c, 0x0a, 0x0b, 0x4f, 0x68, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x68, 0x69, 0x6b, 0x61, 0x72, 0x6f, 0x6f, 0x66, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ohlc_proto_rawDescOnce sync.Once
	file_ohlc_proto_rawDescData = file_ohlc_proto_rawDesc
)

func file_ohlc_proto_rawDescGZIP() []byte {
	file_ohlc_proto_rawDescOnce.Do(func() {
		file_ohlc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ohlc_proto_rawDescData)
	})
	return file_ohlc_proto_rawDescData
}

var file_ohlc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ohlc_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: pb.Request
	(*Summary)(nil), // 1: pb.Summary
}
var file_ohlc_proto_depIdxs = []int32{
	0, // 0: pb.OhlcService.GetSummaryStock:input_type -> pb.Request
	1, // 1: pb.OhlcService.GetSummaryStock:output_type -> pb.Summary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ohlc_proto_init() }
func file_ohlc_proto_init() {
	if File_ohlc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ohlc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Summary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ohlc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ohlc_proto_goTypes,
		DependencyIndexes: file_ohlc_proto_depIdxs,
		MessageInfos:      file_ohlc_proto_msgTypes,
	}.Build()
	File_ohlc_proto = out.File
	file_ohlc_proto_rawDesc = nil
	file_ohlc_proto_goTypes = nil
	file_ohlc_proto_depIdxs = nil
}
