rules:
  stock: ["BBCA", "BBRI", "ASII", "GOTO"]
dataStreamer:
  path: "./resouces/data_source/subsetdata"
redis:
  host: "localhost:6379"
  password: "secret_redis"
  database: 0
  ttl: -1
database:
  host: localhost
  port: 3306
  user: default
  pass: secret
  databaseName: default
  charset: utf8mb4
  debugLog: true
  pool:
    maxConnLifetime: 1m
    maxIdleConn: 5
    maxOpenConn: 50